// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  About_UsApp.swift
//  About Us
//
//  Created by Jia Chen Yee on 15/6/22.
//

import SwiftUI

@main
struct About_UsApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
